export { default as About } from "./About"
export { default as Certifications } from "./Certifications"
export { default as Contact } from "./Contact"
export { default as Profile } from "./Profile"
export { default as Projects } from "./Projects"
export { default as Skills } from "./Skills"
